import React, { useState, useContext } from "react";
import { LanguageContext } from "../../App.js";
import {
  View,
  Text,
  Image,
  StyleSheet,
  Dimensions,
  ScrollView,
  ImageBackground,
  FlatList,
  SafeAreaView,
  Pressable,
  Modal,
} from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import global from "../../resources/global.json";

// Speaker24
export const speaker24 = [
  {
    id: "1",
    name: "Alessia Dapoto",
    image: require("../images/speakers24/dapoto.png"),
    time: "10:40",
    speechTitle: "Titolo 1",
    bioIta:
      "23 anni, studentessa al corso internazionale di medicina della Sapienza. Ha vissuto tra Francia, Germania e Italia, dove ha studiato e fatto ricerca. Scrittrice, poliglotta, attrice, musicista, past president un’associazione giovanile del Rotary International e membro dello European Youth Parliament.",
    bioEng: "...",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "...",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "2",
    name: "Nicola Armaroli ",
    image: require("../images/speakers24/armaroli.webp"),
    time: "11:00",
    speechTitle: "Titolo 2",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "3",
    name: "Abbozzo",
    image: require("../images/speakers24/abbozzo.webp"),
    time: "11:20",
    speechTitle: "Titolo 3",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "4",
    name: "Lorenzo Nardi",
    image: require("../images/speakers24/nardi.webp"),
    time: "11:40",
    speechTitle: "Titolo 4",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "5",
    name: "Break",
    image: require("../images/paradoxalabirinth.png"),
    time: "12:00",
  },
  {
    id: "6",
    name: "Lorenzo Saltarelli",
    image: require("../images/speakers24/saltarelli.webp"),
    time: "12:20",
    speechTitle: "Titolo 6",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "7",
    name: "Esmeralda Moretti",
    image: require("../images/speakers24/moretti.webp"),
    time: "12:40",
    speechTitle: "Titolo 7",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "8",
    name: "Pepa Pasatu",
    image: require("../images/speakers24/pasatu.png"),
    time: "13:00",
    speechTitle: "Titolo 8",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "9",
    name: "Pausa pranzo",
    image: require("../images/paradoxalabirinth.png"),
    time: "13:30 - 15:00",
  },
  {
    id: "10",
    name: "Riccardo Azzali",
    image: require("../images/speakers24/azzali.png"),
    time: "15:00",
    speechTitle: "Titolo 10",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "11",
    name: "Carmen Panepinto Zayati",
    image: require("../images/speakers24/panepinto.webp"),
    time: "15:20",
    speechTitle: "Titolo 11",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
  {
    id: "12",
    name: "Kento",
    image: require("../images/speakers24/kento.png"),
    time: "15:40",
    speechTitle: "Titolo 12",
    bioIta: "Bio in italiano ",
    bioEng: "Bio in inglese",
    resumeIta:
      "Esploreremo un paradosso affascinante: cerchiamo tante esperienze nel mondo esterno ma a volte trascuriamo il viaggio più importante, quello interiore. Ci accompagnerà tra neuroscienze e medicina per scoprire come l’educazione emotiva può trasformare noi stessi e la società, rivoluzionando il mondo.",
    resumeEng: "",
    speechIta: "discorso in italiano",
    speechEng: "discorso in inglese",
  },
];
