import React, { useState, useContext } from "react";
import { LanguageContext } from "../../App.js";
import {
  View,
  Text,
  Image,
  StyleSheet,
  Dimensions,
  ScrollView,
  ImageBackground,
  FlatList,
  SafeAreaView,
  Pressable,
  Modal,
} from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import global from "../../resources/global.json";

//speaker23
export const speaker23 = [
    {
      id: "1",
      name: "Alessia Dapoto",
      image: require("../images/speakers23/dapoto.webp"),
      time: "10:40",
      speechTitle: "Titolo 1",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",

    },
    {
      id: "2",
      name: "Nicola Armaroli ",
      image: require("../images/speakers23/armaroli.webp"),
      time: "11:00",
      speechTitle: "Titolo 2",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "3",
      name: "Abbozzo",
      image: require("../images/speakers23/abbozzo.webp"),
      time: "11:20",
      speechTitle: "Titolo 3",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "4",
      name: "Lorenzo Nardi",
      image: require("../images/speakers23/nardi.webp"),
      time: "11:40",
      speechTitle: "Titolo 4",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "5",
      name: "Break",
      image: require("../images/speakers23/nardi.webp"),
      time: "12:00",
      speechTitle: "Titolo 5",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "6",
      name: "Lorenzo Saltarelli",
      image: require("../images/speakers23/saltarelli.webp"),
      time: "12:20",
      speechTitle: "Titolo 6",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "7",
      name: "Nome Moretti",
      image: require("../images/speakers23/moretti.webp"),
      time: "12:40",
      speechTitle: "Titolo 7",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "8",
      name: "Pepa Pasatu",
      image: require("../images/speakers23/pasatu.webp"),
      time: "13:00",
      speechTitle: "Titolo 8",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "9",
      name: "Pausa pranzo",
      image: require("../images/speakers23/pasatu.webp"),
      time: "!3:30 - 15:00",
      speechTitle: "Titolo 9",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "10",
      name: "Riccardo Azzali",
      image: require("../images/speakers23/azzali.webp"),
      time: "15:00",
      speechTitle: "Titolo 10",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "11",
      name: "Carmen Panepinto",
      image: require("../images/speakers23/panepinto.webp"),
      time: "15:20",
      speechTitle: "Titolo 11",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
    {
      id: "12",
      name: "Kento",
      image: require("../images/speakers23/kento.webp"),
      time: "15:40",
      speechTitle: "Titolo 12",
      bioIta: "Bio in italiano ",
      bioEng: "Bio in inglese",
      speechIta: "discorso in italiano",
      speechEng: "discorso in inglese",
    },
  ];